[build]
  command = "echo 'Build completed'"
  functions = "netlify/functions"
  publish = "."

# Proxy for Socket.IO to bypass CORS
[[redirects]]
  from = "/.netlify/functions/api/socket.io/*"
  to = "https://prima789.net/socket.io/:splat"
  status = 200
  force = true

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Headers for HTML files (LIFF-friendly)
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"

# Headers for Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-LINE-User-ID"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
