# netlify.toml - Production-ready Netlify configuration

[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
